name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    uses: scottobert/deployment-pipeline/.github/workflows/test.yml@main

  sonar:
    needs: test
    uses: scottobert/deployment-pipeline/.github/workflows/sonar.yml@main
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  release:
    needs: [test, sonar]
    if: github.event_name == 'push'
    permissions:
      id-token: write  # Required for OIDC
      contents: write
      packages: write
    uses: scottobert/deployment-pipeline/.github/workflows/semantic-release.yml@main
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
