name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    uses: scottobert/deployment-pipeline/.github/workflows/test.yml@main

  # sonar:
  #   needs: test
  #   uses: scottobert/deployment-pipeline/.github/workflows/sonar.yml@main
  #   secrets:
  #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  release:
    needs: [test] #, sonar]
    if: github.event_name != 'pull_request' # Don't run release on pull request events
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for trusted publishing and npm provenance
    uses: scottobert/deployment-pipeline/.github/workflows/semantic-release.yml@main
    with:
      node-version: 'lts/*'
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
